// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
std::shared_ptr<frc::SpeedController> RobotMap::mecanum1FrontLeft;
std::shared_ptr<frc::SpeedController> RobotMap::mecanum1RearLeft;
std::shared_ptr<frc::SpeedController> RobotMap::mecanum1FrontRight;
std::shared_ptr<frc::SpeedController> RobotMap::mecanum1RearRight;
std::shared_ptr<frc::MecanumDrive> RobotMap::mecanum1MecanumDrive1;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    frc::LiveWindow *lw = frc::LiveWindow::GetInstance();

    mecanum1FrontLeft.reset(new frc::Spark(1));
    lw->AddActuator("Mecanum1", "Front Left", std::static_pointer_cast<frc::Spark>(mecanum1FrontLeft));
    
    mecanum1RearLeft.reset(new frc::Spark(3));
    lw->AddActuator("Mecanum1", "Rear Left", std::static_pointer_cast<frc::Spark>(mecanum1RearLeft));
    
    mecanum1FrontRight.reset(new frc::Spark(0));
    lw->AddActuator("Mecanum1", "Front Right", std::static_pointer_cast<frc::Spark>(mecanum1FrontRight));
    
    mecanum1RearRight.reset(new frc::Spark(2));
    lw->AddActuator("Mecanum1", "Rear Right", std::static_pointer_cast<frc::Spark>(mecanum1RearRight));
    
    mecanum1MecanumDrive1.reset(new frc::MecanumDrive(*mecanum1FrontLeft, *mecanum1RearLeft,
              *mecanum1FrontRight, *mecanum1RearRight));
    lw->AddActuator("Mecanum1", "Mecanum Drive 1", mecanum1MecanumDrive1);
    mecanum1MecanumDrive1->SetSafetyEnabled(true);
        mecanum1MecanumDrive1->SetExpiration(0.1);
        mecanum1MecanumDrive1->SetMaxOutput(1.0);


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
